#ifndef _JOYFIX_H_
#define _JOYFIX_H_

enum {
    JOYBUT_TRIANGLE,
    JOYBUT_CIRCLE,
    JOYBUT_CROSS,
    JOYBUT_SQUARE,
    JOYBUT_LTRIGGER,
    JOYBUT_RTRIGGER,
    JOYBUT_DOWN,
    JOYBUT_LEFT,
    JOYBUT_UP,
    JOYBUT_RIGHT,
    JOYBUT_SELECT,
    JOYBUT_START,
    JOYBUT_HOME,
    JOYBUT_HOLD
};

#endif
