; Code generated by lcc v4.0 (ARM/RISC OS back-end v1.12q Stu Smith)

;	Stack checking  -- on
;	Faster locals   -- on
;	Using FREGs     -- off
;	Saving FP regs  -- off

	RN:		a1	0
	RN:		a2	1
	RN:		a3	2
	RN:		a4	3
	RN:		v1	4
	RN:		v2	5
	RN:		v3	6
	RN:		v4	7
	RN:		v5	8
	RN:		v6	9
	RN:		sl	10
	RN:		fp	11
	RN:		ip	12
	RN:		sp	13
	RN:		lr	14
	RN:		pc	15
	FN:		f0	0
	FN:		f1	1
	FN:		f2	2
	FN:		f3	3
	FN:		f4	4
	FN:		f5	5
	FN:		f6	6
	FN:		f7	7

	TEMP:		lr

	CREATOR:	"[lcc v4.0 (ARM/RISC OS back-end v1.12q Stu Smith)]"


	EXPORT:		|main|

	SEGMENT:	CODE

	; FUNCTION: |main|
	; framesize = 4,  ncalls = 2
	; maxargoffset = 0, maxoffset = 4
	; fourstore = 0

	SEGMENT:	CODE
|main|
	mov	ip, sp
	stmfd	sp!, {v6, fp, ip, lr, pc}
	sub	fp, ip, #4
	cmp	sp, sl
	bllt	x$stack_overflow
	sub	sp, sp, #4
	mov	v6, #123
	mov	ip, #324
	mul	ip, ip, v6
	add	ip, v6, ip
	str	ip, [sp, #-4+4]
	adr	a1, |L.2|
	bl	|printf|
|.L.1|
	ldmea	fp, {v6, fp, sp, pc}^


	SEGMENT:	LIT
|L.2|
	; string = "hell!\n\0"
	dcb	0x68, 0x65, 0x6c, 0x6c, 0x21, 0x0a, 0x00

	; Compilation complete.
